
services:
  - type: web
    name: djangochat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn djangochat.wsgi:application
    runtime: python
    pythonVersion: 3.10
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
